name: Rust Tests on QEMU x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: sudo apt install qemu-user qemu-system-x86 -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
