name: Rust Tests on QEMU x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: install Qemu
      run: sudo apt install qemu-user qemu-system-x86 -y
    - name: install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: source env file
      run: . /"$HOME/.cargo/env"
    - name: install rust nightly
      run: rustup toolchain install nightly
    - name: install nightly-aarch64-unknown-linux-gnu toolchain
      run: rustup component add rust-src --toolchain nightly-aarch64-unknown-linux-gnu
    - name: install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: install bootimage
      run: cargo install bootimage
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
